### ISSUE TITLE
Propozycje do uporządkowania kodu

### ISSUE THREAD

**Issue by SebastianCelejewski** [openpkw/openpkw-weryfikator#19]
Kilka propozycji z mojej strony:
- Wybór środowiska, względem którego uruchamiane są automatyczne testy akceptacyjne przy pomocy parametrów Mavena, np. -Dopenpkw-env=test, aby strzelał w Dobromira, -Dopenpkw-env=local, aby strzelał w localhost.
- Przejrzenie nazw tabel i kolumn w encjach.
- Wprowadzenie log4j we wszystkich miejscach, gdzie jest System.out.println().
- Przeniesienie wszelkiej logiki biznesowej do projektu openpkw-services.
- Dostosowanie kodu aplikacji Androidowej, aby korzystała z najnowszych wersji API do tworzenia użytkowników, logowania się do systemu i wysyłania kodów QR.

Dopisujcie swoje propozycje:

**Comment by SebastianCelejewski** [comment]
Oprócz tego wszystkie sprawy związane z RESTem (w osobnym issue pt. ,,Opracowanie koncepcji ogólnej dla REST'').

**Comment by adamkowalewski** [comment]
Odnośnie trzeciego punktu: odradzam bazowanie na `log4j`w środowisku kontenera JEE. WildFly na dzień dobry oferuję [slf4j](https://github.com/wildfly/wildfly/blob/3fbeffe9495e0a7073eedd4a5bfb3a1de6d8f201/pom.xml#L212) jako `provided`. 
```xml
<dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>${version.slf4j}</version>
      <scope>provided</scope>
</dependency> 
```

**Comment by SebastianCelejewski** [comment]
Dzięki za poradę.

Problem tkwi jednak w tym, że część kodu to są toole do uruchamiania z command line i takie rozwiązanie nie działa. I teraz mamy wybór albo będziemy używać dwóch podejść (slf4j i log4j), albo wybierzemy jedno, spójnie dla całego komponentu (i wtedy będzie to log4j).

**Comment by pogos** [comment]
Jaki jest problem z slf4j w aplikacjach command line?. W jaki sposób uruchamiasz tool z command line? Moim zdaniem możliwe, że brakuje zależności na classpath.

slf4j to jedynie API pod którym w naszej aplikacji i tak ukrywa się log4j.

**Comment by SebastianCelejewski** [comment]
Jeszcze mam jedną propozycję do ewentualnego refactoringu: pozbycie się Spring Application Framework i przejście na czystą Java EE. Dałoby to m. in. znaczną redukcję wynikowych jarów, a w związku z tym szybsze deploymenty.

**Comment by mrozim78** [comment]
Myślę że to musimy przedyskutować we wtorek bo mam kilka wątpliwości co do tego pomysłu.

**Comment by SebastianCelejewski** [comment]
Czy możemy to issue zamknąć? Chyba jest stara i dawno wykonana.

**Comment by SebastianCelejewski** [comment]
Stwierdzam timeout - zamykam.
